##
# @description Publish page automation
# @author      C. M. de Picciotto <d3p1@d3p1.dev> (https://d3p1.dev/)
# @link        https://www.freecodecamp.org/news/how-to-deploy-next-js-app-to-github-pages/
# @note        The `concurrency` setting allows us to run only one
#              concurrent deployment, and it does not cancel `in-progress` runs
##
name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages   : write
  id-token: write

concurrency:
  group             : "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout️
        uses: actions/checkout@v4

      - name : Setup base directory
        shell: bash
        run  : cd www

      - name: Setup Node.js
        uses: ./.github/workflows/utils/setup-node

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      - name: Build Next.js️
        run : npx next build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url : ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Publish to GitHub Pages
        id  : deployment
        uses: actions/deploy-pages@v4